### ISSUE TITLE
Which Python 3.x version do we settle on and do we need to support 2.7 ?

### ISSUE THREAD

**Issue by krzysztof** [asclepias/asclepias-broker#15]
I've been looking into what's coming in Python 3.7: https://www.python.org/downloads/release/python-370b1/ and realized we're not using most of the Python 3.x features.

Do we have any restrictions on minimal supported Python version?

**Comment by augustfly** [comment]
Do you mean which point release of Python 3? @astrofrog

**Comment by krzysztof** [comment]
Yes, but mostly whether or not we need to be compatible with Python 2.7. I guess since this would be a rather stand-alone service we can probably not support 2.7, unless anyone has this requirement.

If we intend to use some of the invenio modules, e.g. for boostrapping accounts, permissions, webhooks, etc., we can use anything between 2.7 and 3.5 (currently supported versions).

**Comment by astrofrog** [comment]
Python 3.5+ sounds good to me!

**Comment by slint** [comment]
The project has been updated to use Python 3.6
