### ISSUE TITLE
"Fork me on GitHub" link broken

### ISSUE THREAD

**Issue by ocaisa** [asclepias/asclepias-broker#65]
The link in the top right of https://asclepias-broker.readthedocs.io/en/latest/ is broken, I think you need to change https://github.com/asclepias/asclepias-broker/blob/master/docs/conf.py#L127 (but I'm no expert)

**Comment by Glignos** [comment]
Fixed by: https://github.com/asclepias/asclepias-broker/commit/1764e347ecae1c4a0c2131bd89d6ed9428c3a438
