### ISSUE TITLE
Dev: Deploy Current version of broker to Azure test environment

### ISSUE THREAD

**Issue by mubdi** [asclepias/asclepias-broker#85]
Deploy current version of Asclepias Broker to Azure VM, fixing the install/deploy requirements/versions.

**Comment by mattiaswangblad** [comment]
I've managed to spin up a version of the broker now. I've just done a very short ingestion so far.
See https://asclepias-broker-node.eastus.cloudapp.azure.com/relationships?id=10.5281/zenodo.11020&scheme=doi&relation=isCitedBy&sort=-mostrecent&group_by=identity&size=10&page=1 for a test sample

**Comment by mubdi** [comment]
This looks good, and is actively working!
